import Head from 'next/head';
import Feed from './components/feed';
import Sidebar from './components/Sidebar';
import Widgets from './components/Widgets';

export default function Home({newsResults}) {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main className="flex min-h-screen mx-auto">
       {/*Side Bar*/}
       <Sidebar />



{/*Feed Section*/}
    <Feed />

{/*Widgets*/}
    <Widgets newsResults={newsResults.articles} />


{/*Modals*/}


    </main>
     

    </div>
  )
}


//https://saurav.tech/NewsAPI/top-headlines/category/sports/us.json

export async function getServerSideProps(){
  const newsResults = await fetch("https://saurav.tech/NewsAPI/top-headlines/category/health/gb.json").then((res)=>res.json());
  return {
    props: {
      newsResults
    }
  }
}